spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:h2:file:./db
    username: root
    password: 1111
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false

